#:kivy 2.1.0

#:import NoTransition kivy.uix.screenmanager.NoTransition
#:include screen_home.kv
#:include screen_login.kv
#:include screen_main.kv
#:include screen_menu.kv
#:include screen_wtm.kv
#:include screen_slm.kv


# ScreenManager:
<RootScreen>:
    id: screen_manager
    transition: NoTransition()

    ScreenHome:
        id: screen_home
        name: 'screen_home'
        screen_manager: screen_manager
        
    ScreenLogin:
        id: screen_login
        name: 'screen_login'
        screen_manager: screen_manager

    ScreenMain:
        id: screen_main
        name: 'screen_main'
        screen_manager: screen_manager
    
    ScreenMenu:
        id: screen_menu
        name: 'screen_menu'
        screen_manager: screen_manager

    ScreenWTM:
        id: screen_wtm
        name: 'screen_wtm'
        screen_manager: screen_manager   

    ScreenSLM:
        id: screen_slm
        name: 'screen_slm'
        screen_manager: screen_manager
  