#:kivy 2.1.0

<ScreenHLM>:
    MDBoxLayout:
        orientation: "vertical"

		# header layout
        MDBoxLayout:
            id: header_layout
            orientation: "horizontal"
            padding: 20
			spacing: 20
			size_hint_y: 0.2
			md_bg_color: "#111111"
                    
            Image:
                id: logo
                source:'assets/images/logo-trb.png'
                size_hint_x: 0.15
                allow_stretch: True 

			MDBoxLayout:
				orientation: "vertical"
				size_hint_x: 0.7

				MDLabel:
					id: lb_title            
					text: "VEHICLE INSPECTION INTEGRATION MANAGEMENT SYSTEM"
					halign: "left"
					valign: "middle"
					font_style: 'H4'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"


				MDLabel:
					id: lb_subtitle            
					text: "AXLE LOAD & BRAKE METER"
					halign: "left"
					valign: "middle"
					font_style: 'H5'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

			MDBoxLayout:
				orientation: "vertical"
				size_hint_x: 0.15

				MDLabel:
					id: lb_time
					text: "12:34:00"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

				MDLabel:
					id: lb_date
					text: "17/08/2024"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

				MDLabel:
					id: lb_operator
					text: "Nama Operator"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"
					text_color: "#FFFFFF"

				MDLabel:
					id: lb_comm
					text: "Com: Tidak Terhubung"
					halign: "center"
					valign: "middle"
					font_style: 'H6'
					theme_text_color: "Custom"

        # ------------------- KONTEN UTAMA -------------------
        MDBoxLayout:
            id: layout_main
            orientation: "horizontal"
            size_hint_y: 0.7
            padding: 20
            spacing: 20

            # --- PANEL KIRI ---
            MDBoxLayout:
                orientation: "vertical"
                size_hint_x: 0.35
                padding: 10
                spacing: 15
                MDCard:
                    orientation: "vertical"
                    padding: "10dp"
                    spacing: "8dp"
                    adaptive_height: True
                    MDLabel:
                        text: "IDENTITAS KENDARAAN"
                        halign: "center"
                        font_style: 'H6'
                        size_hint_y: None
                        height: self.texture_size[1]
                    MDSeparator:
                    MDBoxLayout:
                        adaptive_height: True
                        MDLabel:
                            text: "No. Antrian"
                        MDLabel:
                            id: lb_no_antrian
                            text: "-"
                            halign: "right"
                    MDBoxLayout:
                        adaptive_height: True
                        MDLabel:
                            text: "No. Polisi"
                        MDLabel:
                            id: lb_no_pol
                            text: "-"
                            halign: "right"
                    MDBoxLayout:
                        adaptive_height: True
                        MDLabel:
                            text: "No. Uji"
                        MDLabel:
                            id: lb_no_uji
                            text: "-"
                            halign: "right"
                MDCard:
                    orientation: "vertical"
                    padding: "10dp"
                    spacing: "10dp"
                    adaptive_height: True
                    MDBoxLayout:
                        adaptive_height: True
                        MDRectangleFlatIconButton:
                            id: btn_jauh
                            icon: "car-light-high"
                            text: "LAMPU JAUH"
                            size_hint_x: 1
                            on_release: root.select_beam("jauh")
                        MDRectangleFlatIconButton:
                            id: btn_dekat
                            icon: "car-light-dimmed"
                            text: "LAMPU DEKAT"
                            size_hint_x: 1
                            on_release: root.select_beam("dekat")
                    MDBoxLayout:
                        adaptive_height: True
                        MDRectangleFlatIconButton:
                            id: btn_kiri
                            icon: "arrow-left-bold-outline"
                            text: "KIRI"
                            size_hint_x: 1
                            on_release: root.select_side("kiri")
                        MDRectangleFlatIconButton:
                            id: btn_kanan
                            icon: "arrow-right-bold-outline"
                            text: "KANAN"
                            size_hint_x: 1
                            on_release: root.select_side("kanan")
                            
                MDCard:
                    orientation: "vertical"
                    size_hint_y: None
                    height: "100dp"
                    padding: "10dp"
                    md_bg_color: "#4f4f4fff"
                    MDLabel:
                        text: "STATUS PENGUJIAN"
                        halign: "center"
                        theme_text_color: "Custom"
                        text_color: "white"
                    MDLabel:
                        id: lb_test_result
                        text: "-"
                        halign: "center"
                        font_style: 'H4'
                        theme_text_color: "Custom"
                        text_color: "white"
                Widget:

            MDBoxLayout:
                orientation: "vertical"
                size_hint_x: 0.65
                spacing: 15
                MDCard:
                    orientation: "vertical"
                    padding: "15dp"
                    spacing: "10dp"
                    adaptive_height: True
                    MDLabel:
                        id: lb_info_bagian
                        text: "Bagian Diuji: -"
                        halign: "center"
                        font_style: "H6"
                    MDSeparator:
                    MDBoxLayout:
                        adaptive_height: True
                        MDLabel:
                            text: "Daya Pancar Terukur:"
                            size_hint_x: 0.5
                        MDLabel:
                            id: lb_info_daya
                            text: "- Cdl"
                            halign: "right"
                            size_hint_x: 0.3
                        # PERBAIKAN: Label status baru untuk Daya
                        MDLabel:
                            id: lb_info_daya_status
                            text: "(-)"
                            halign: "right"
                            size_hint_x: 0.2
                            theme_text_color: "Custom"
                            text_color: "white"
                            bold: True
                    MDBoxLayout:
                        adaptive_height: True
                        MDLabel:
                            text: "Penyimpangan Terukur:"
                            size_hint_x: 0.5
                        MDLabel:
                            id: lb_info_penyimpangan
                            text: "-"
                            halign: "right"
                            size_hint_x: 0.3
                        # PERBAIKAN: Label status baru untuk Penyimpangan
                        MDLabel:
                            id: lb_info_penyimpangan_status
                            text: "(-)"
                            halign: "right"
                            size_hint_x: 0.2
                            theme_text_color: "Custom"
                            text_color: "white"
                            bold: True
                MDCard:
                    md_bg_color: "black"
                    MDFloatLayout:
                        id: layout_camera_container
                        Image:
                            id: camera_view
                            fit_mode: "contain"
                            size_hint: 1, 1
                            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                        MDLabel:
                            id: lb_countdown
                            text: ""
                            font_style: "H1"
                            halign: "center"
                            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                            theme_text_color: "Custom"
                            text_color: "yellow"
                MDBoxLayout:
                    orientation: "horizontal"
                    size_hint_y: None
                    height: "40dp"
                    spacing: "10dp"
                    MDRectangleFlatIconButton:
                        icon: "camera-outline"
                        text: "BUKA"
                        size_hint_x: 1
                        theme_text_color: "Custom"
                        text_color: "#FFFFFF"
                        md_bg_color: "#222a2cff"
                        on_release: root.exec_open_camera()
                    MDRectangleFlatIconButton:
                        icon: "play-circle-outline"
                        text: "MULAI"
                        size_hint_x: 1
                        theme_text_color: "Custom"
                        text_color: "#FFFFFF"
                        md_bg_color: "#195abbff"
                        on_release: root.exec_start_test()
                    MDRectangleFlatIconButton:
                        icon: "content-save"
                        text: "SIMPAN"
                        size_hint_x: 1
                        theme_text_color: "Custom"
                        text_color: "#FFFFFF"
                        md_bg_color: "#08b021ff"
                        on_release: root.exec_save()
                    MDRectangleFlatIconButton:
                        icon: "keyboard-return"
                        text: "KEMBALI"
                        size_hint_x: 1
                        theme_text_color: "Custom"
                        text_color: "#FFFFFF"
                        md_bg_color: "#de2020ff"
                        on_release: root.exec_navigate_main()

		# footer layout
        MDBoxLayout:
            orientation: "horizontal"
			size_hint_y: 0.1

			MDBoxLayout:
				orientation: "horizontal"
				padding: 20
				spacing: 20
				md_bg_color: "#4471C4"
				size_hint_x: 0.4
				
				AsyncImage:
					id: img_pemkab
					source:'assets/images/logo-sorong.png'
					size_hint_x: 0.1
					allow_stretch: True  

				AsyncImage:
					id: img_dishub
					source:'assets/images/logo-dishub.png'
					size_hint_x: 0.1
					allow_stretch: True  

				MDBoxLayout:
					orientation: "vertical"
					size_hint_x: 0.8

					MDLabel:
						id: lb_pemkab
						text: "PEMERINTAH KABUPATEN SORONG"
						halign: "left"
						valign: "middle"
						theme_text_color: "Custom"
						text_color: "#EEEEEE"						
						font_style: 'Subtitle1'

					MDLabel:
						id: lb_dishub
						text: "DINAS PERHUBUNGAN"
						halign: "left"
						valign: "middle"
						theme_text_color: "Custom"
						text_color: "#EEEEEE"
						font_style: 'Subtitle1'

					MDLabel:
						id: lb_unit			
						text: "UNIT PELAKSANA UJI BERKALA KENDARAAN BERMOTOR"
						halign: "left"
						valign: "middle"
						theme_text_color: "Custom"
						text_color: "#EEEEEE"
						font_style: 'Subtitle1'

					MDLabel:
						id: lb_unit_address
						text: " Klamasen, Distrik Mariat, Kabupaten Sorong, Papua Barat Daya. 98416"
						halign: "left"
						valign: "middle"
						md_bg_color: "#EEEEEE"
						theme_text_color: "Custom"
						text_color: "#000000"
						font_style: 'Subtitle1'

			MDBoxLayout:
				orientation: "vertical"
				padding: 20
				spacing: 20
				md_bg_color: "#FFC000"
				size_hint_x: 0.6

				MDLabel:			
					text: "INFORMASI"
					halign: "left"
					valign: "middle"
					font_style: 'H5'

				MDLabel:
					id: lb_info
					text: "Standar pengujian sesuai PERATURAN MENTERI LINGKUNGAN HIDUP DAN KEHUTANAN REPUBLIK INDONESIA N0 8 TAHUN 2023"
					halign: "left"
					valign: "middle"
					font_style: 'H6'